### -create a user
POST http://localhost:3000/api/users/create HTTP/1.1
Content-Type: application/json

{
    "email": "dfsdf@gmail.com",
    "password": "lkjasd321",
    "name": "hfgh",
    "lastName": "zarfghfgagosa",
    "role": "user"
}




### - verify account 
GET http://localhost:3000/api/email/verify?token=eyJhbGciJIUzI1NiJ9.bW9yYWJydW5vQGdtYWlsLmNvbQ.AOMPu-xl3fmgMQZB_QmHVKsQrerocKRrJiyU3N8DXhY HTTP/1.1




### -get a single user
GET http://localhost:3000/api/users/6079117fc7aa892158938746 HTTP/1.1




### - login user
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "dfsdf@gmail.com",
    "password": "lkjasd321"
}




### - update user
PUT http://localhost:3000/api/users/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc5MTE3ZmM3YWE4OTIxNTg5Mzg3NDYiLCJuYW1lIjoiZW5lcnN0byIsImxhc3ROYW1lIjoiemFyYWdvc2EiLCJlbWFpbCI6ImVybmVzdG9AZ21haWwuY29tIiwiaWF0IjoxNjE4NTQ3MzE2fQ.JqJiF0BqTcrUZIkftKIum6niCUEpqGoNeopklaWEG3o
