### -create a user
POST http://localhost:3000/api/users/create HTTP/1.1
Content-Type: application/json

{
    "name": "bruno",
    "lastName": "mora",
    "email": "sadxcxddsfz@gmail.com",
    "password": "34dfg35",
    "role": "user"
}




### -get a single user
GET http://localhost:3000/api/users/6077d5a349401c1890ddd8ed HTTP/1.1




### - login user
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "sadxcxddsfz@gmail.com",
    "password": "34dfg35"
}




### - update user
PUT http://localhost:3000/api/users/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc3ZDVhMzQ5NDAxYzE4OTBkZGQ4ZWQiLCJuYW1lIjoiYnJ1bm8iLCJsYXN0TmFtZSI6Im1vcmEiLCJlbWFpbCI6InNhZHhjeGRkc2Z6QGdtYWlsLmNvbSIsImlhdCI6MTYxODQ2NzU5M30.qq8SFsMp_41Jg0e0cGQnxEHJyKU4i9lQLlJHjP4D5p0

